add mypy annotations
twisted/incremental pull request #69
Opened 2021-03-21 13:51 UTC by graingert

2021-03-21 14:25 UTC, graingert commented on src/incremental/__init__.py
> -    Class decorator that ensures support for the special C{__cmp__} method.
this decorator is broken on mypy - and the type annotations are slightly different,

eg Version is only comparable with other Versions

2021-03-21 14:29 UTC, graingert commented on src/incremental/update.py
> +            ) = release
```suggestion
            major, minor = release
```

2021-03-21 16:05 UTC, graingert commented on src/incremental/update.py
> +    class FilePath(object):
FilePath is type annotated in twisted, but it's decorated with `twisted.python.comparable` which strips the annotations

2021-03-22 18:26 UTC, altendky requested changes

2021-03-22 18:26 UTC, altendky commented on src/incremental/update.py
> +            major, minor, micro = release
If only Python 3...  oh well.

```python
if len(release) > 3:
    raise Exception("ack!")

major, minor, micro, [_] = [*release, 0, 0, 0]
```

2021-03-22 18:27 UTC, graingert commented on pyproject.toml
> +target-version = ['py27', 'py36', 'py37', 'py38', 'py38']
black doesn't support py39 as a target

2021-03-22 18:33 UTC, graingert commented on src/incremental/__init__.py
> +    if sys.version_info >= (3, 0):
I don't know - I was planning on dropping py2.7 support and not thinking about it

2021-03-22 18:35 UTC, graingert commented on src/incremental/update.py
> +    _path = FilePath(path) if path else _findPath(_getcwd(), package)
mypy doesn't let you redefine an `Optional[str]` as an `FilePath`

2021-03-22 18:39 UTC, graingert commented on src/incremental/update.py
> +    class FilePath(object):
```suggestion
    # FilePath is missing type annotations
    # https://twistedmatrix.com/trac/ticket/10148
    class FilePath(object):
```

2021-03-22 19:54 UTC, graingert commented on pyproject.toml
> +target-version = ['py27', 'py36', 'py37', 'py38', 'py38']
```suggestion
target-version = ['py27', 'py36', 'py37', 'py38']
```

2021-03-22 20:01 UTC, altendky approved these changes
Approved pending CI success.

2021-03-22 20:23 UTC, merged